version: '3.3'

services:
  backend:
    build: ./silant
    command:
      gunicorn silant.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - ./silant/:/usr/src/app/
      - myStatic:/home/static
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - backend
    volumes:
      - myStatic:/home/static
volumes:
  myStatic:


