version: '3.3'

services:
  backend:
    build: ./silant
    command:
      gunicorn silant.wsgi:application --bind 0.0.0.0:8000
    #      python manage.py runserver 0.0.0.0:8000
    #    ports:
    #      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env
    volumes:
      - ./silant/:/usr/src/app/
      - myStatic:/home/static
  nginx:
    build: ./nginx
    ports:
      - 11337:80
    #    expose:
    #      - 11337
    depends_on:
      - backend
    volumes:
      - myStatic:/home/static
  frontend:
    build: ./FRONTEND
    volumes:
      - frontend:/usr/src/frontend/
    depends_on:
      - nginx
  nginx2:
    build: ./FRONTEND/nginx
    volumes:
      - frontend:/usr/src/frontend/
    depends_on:
      - frontend
    ports:
      - 11340:80
volumes:
  myStatic:
  frontend:


